feat: build date picker ui
raymond-le-goldenowl/health-declaration-form pull request #7
Opened 2022-01-25 10:07 UTC by raymond-le-goldenowl

**Task**

Build date picker ui

**Descriptions**

User can select datetime

**Screenshots**
![Screenshot from 2022-01-25 17-00-50](https://user-images.githubusercontent.com/96218923/150956215-a1f716b5-1e70-4078-b280-3f078a4d62de.png)

2022-02-24 10:07 UTC, jun-nguyen-goldenowl requested changes

2022-02-24 10:07 UTC, jun-nguyen-goldenowl commented on src/app/components/DatePickerCustom/index.jsx
> +						: moment(moment(moment()._d).format(DATE_FORMAT), DATE_FORMAT)
is there any other simple way?

2022-02-25 03:46 UTC, raymond-le-goldenowl commented on src/app/components/DatePickerCustom/index.jsx
> +						: moment(moment(moment()._d).format(DATE_FORMAT), DATE_FORMAT)
i can use something like this 
```js 
defaultDateTime ? moment(defaultDateTime, DATE_FORMAT) : moment(new Date(), DATE_FORMAT)
```

2022-03-03 07:42 UTC, ApolloRisky requested changes

2022-03-03 07:42 UTC, pwn-0x309 commented on src/app/components/DatePickerCustom/index.jsx
> +	const handleOnchange = value => onChange && onChange(moment(value).format(DATE_FORMAT));
use optional chaining syntax instead

2022-03-03 07:42 UTC, pwn-0x309 commented on src/app/components/DatePickerCustom/index.jsx
> +	const handleOnchange = value => onChange && onChange(moment(value).format(DATE_FORMAT));
```suggestion
	const handleOnchange = value => onChange?.(moment(value).format(DATE_FORMAT));
```

2022-03-21 17:13 UTC, ApolloRisky approved these changes

2022-03-22 02:41 UTC, merged